#! /usr/bin/bash

set -euox pipefail

pushd deps/googletest

cmake -S . -B build
cmake \
	-DCMAKE_CXX_COMPILER=$(which clang++) \
	-DCMAKE_C_COMPILER=$(which clang) \
	-DCMAKE_CXX_FLAGS="-stdlib=libc++ -fno-rtti" \
	-DCMAKE_C_FLAGS="-stdlib=libc++" \
	. -B build

cmake --build build

sudo cmake --install build
