name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jbrhm/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
      volumes:
        - ${{ github.workspace }}:/work

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Symlink Clang
      run: sudo ln -s /usr/bin/clang++-20 /usr/bin/clang++ && sudo ln -s /usr/bin/clang-20 /usr/bin/clang
    - name: Build Google Test
      run: scripts/build_google_test
    - name: Build Repo
      run: ./build.sh
    - name: Check test cases
      run: build/test_suite
