name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jbrhm/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
      volumes:
        - ${{ github.workspace }}:/work

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build Google Test
      run: scripts/build_google_test

    - name: Build Repo
      run: ./build.sh

    - name: Check Test Cases
      run: build/test_suite

    - name: Check Tidy
      run: scripts/style.sh
